### ISSUE TITLE
Death cases are not appearing after entering as shortcode

### ISSUE THREAD

**Issue by shashwatanayak** [tjthouhid/Corona-India-Live-Update#1]
Death cases are not appearing after entering as shortcode, Please check

**Comment by tjthouhid** [comment]
its depends on the website we are using, will update if the website is change.

**Comment by shashwatanayak** [comment]
The Plugin is gathering data from Covıd19india.org, where Death cases us
present, So can you Please check

**Comment by tjthouhid** [comment]
https://github.com/tjthouhid/Corona-India-Live-Update/releases/tag/1.0.5

please check this version I think its still workingg

**Comment by shashwatanayak** [comment]
Issue Resolved
